name: Image Scan Test
run-name: Image Scan Test
on: 
  - push
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  set-matrix:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::379378515717:role/minoru-saito-github-oidc-role
          role-session-name: MySessionName

      - name: Run Trivy vulnerability scanner output table
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/minoru_test:v2'
          format: 'table'
          # output: 'trivy-results.sarif'
          severity: 'CRITICAL'
        # env:
        #   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        #   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        #   AWS_DEFAULT_REGION: ap-northeast-1
      
      - name: Run Trivy vulnerability scanner output json
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/minoru_test:v2'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL'
        # env:
        #   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        #   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        #   AWS_DEFAULT_REGION: ap-northeast-1
      
      - name: Run Dockle output json
        uses: erzz/dockle-action@v1
        with:
          image: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/minoru_test:v2'
          failure-threshold: fatal
        # env:
        #   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        #   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        #   AWS_DEFAULT_REGION: ap-northeast-1

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name:  Upload Report
          path: trivy-results.json
          
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name:  Upload Report
          path: dockle-report.json

      - uses: at-wat/setup-gh-pr-comment@v0
      - run: gh-pr-comment "title" "message"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
