name: Image Scan Test
run-name: Image Scan Test
on: 
  - push
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# pull_images.csvを読み込んでスキャンイメージをmatrixにセット
jobs:
  set_matrix:
    runs-on: ubuntu-20.04
    outputs:
      images: ${{ steps.get_scan_images.outputs.images }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: get scan images from csvfile
        id: get_scan_images
        run: |
          images = awk -F ',' 'OFS=":" {print $1,$2}' pull-images.csv | tail -n +2 | jq -R -s -c 'split("\n")[:-1]'
          echo "::set-output name=images::${images}"

  Image_Scan:
    needs: set_matrix
    name: Image Scan
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scan_imagas: ${{ fromJson(needs.set_matrix.outputs.images) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::379378515717:role/minoru-saito-github-oidc-role
          # role-session-name: MySessionName

      - name: Run Trivy vulnerability scanner output table
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/${{matrix.scan_imagas}}'
          format: 'table'
          severity: 'CRITICAL'
      
      - name: Run Trivy vulnerability scanner output json
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/${{matrix.scan_imagas}}'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL'
      
      - name: Run Dockle output json
        uses: erzz/dockle-action@v1
        with:
          image: '379378515717.dkr.ecr.ap-northeast-1.amazonaws.com/${{matrix.scan_imagas}}'
          failure-threshold: fatal

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name:  Upload Report
          path: trivy-results.json
          
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name:  Upload Report
          path: dockle-report.json
